import React, { useEffect, useMemo, useRef, useState } from 'react';
import { AlertDialog, AlertDialogBody, AlertDialogContent, AlertDialogFooter, AlertDialogHeader, AlertDialogOverlay, Badge, Box, Button, Flex, FormControl, FormErrorMessage, FormLabel, Grid, IconButton, Input, Menu, MenuButton, MenuItem, MenuList, Modal, ModalBody, ModalCloseButton, ModalContent, ModalHeader, ModalOverlay, Select, Spinner, Table, TableContainer, Tbody, Td, Text, Th, Thead, Tr, useDisclosure, useToast } from '@chakra-ui/react';
import { LuEllipsisVertical, LuPlus } from 'react-icons/lu';
import { Navigate } from 'react-router-dom';
import { isAuthenticated } from '../../utils/session';
import { listarEmpresas } from '../../services/empresas.service';
import { atualizarCentroCusto, criarCentroCusto, inativarCentroCusto, listarCentrosCusto } from '../../services/centrosCusto.service';
const EMPTY_FORM = { empresaId: '', nome: '', codigo: '', status: 'Ativo' };
const getFriendlyError = (e) => e?.data?.message || e?.message || 'Não foi possível concluir a ação.';
function CentroModal({ isOpen, onClose, onSave, initialData, empresas }) { const [form, setForm] = useState(EMPTY_FORM); const [errors, setErrors] = useState({}); useEffect(() => { setForm(initialData ? { ...EMPTY_FORM, ...initialData } : EMPTY_FORM); setErrors({}); }, [isOpen, initialData]); const ch = (e) => setForm((p) => ({ ...p, [e.target.name]: e.target.value })); const salvar = async () => { const next = {}; if (!form.empresaId) next.empresaId = 'Empresa obrigatória'; if (!form.nome?.trim()) next.nome = 'Nome obrigatório'; setErrors(next); if (Object.keys(next).length) return; try { await onSave(form); onClose(); } catch {} };
  return <Modal isOpen={isOpen} onClose={onClose} isCentered><ModalOverlay /><ModalContent><ModalHeader>{initialData ? 'Editar Centro de Custo' : 'Novo Centro de Custo'}</ModalHeader><ModalCloseButton /><ModalBody pb='6'><Grid gap='3'><FormControl isRequired isInvalid={!!errors.empresaId}><FormLabel>Empresa</FormLabel><Select name='empresaId' value={form.empresaId} onChange={ch} placeholder='Selecione a empresa'>{empresas.map((e) => <option key={e.id} value={e.id}>{e.nome}</option>)}</Select><FormErrorMessage>{errors.empresaId}</FormErrorMessage></FormControl><FormControl isRequired isInvalid={!!errors.nome}><FormLabel>Nome</FormLabel><Input name='nome' value={form.nome} onChange={ch} /><FormErrorMessage>{errors.nome}</FormErrorMessage></FormControl><FormControl><FormLabel>Código</FormLabel><Input name='codigo' value={form.codigo} onChange={ch} /></FormControl><FormControl><FormLabel>Status</FormLabel><Select name='status' value={form.status} onChange={ch}><option>Ativo</option><option>Inativo</option></Select></FormControl><Flex justify='flex-end' gap='3'><Button variant='ghost' onClick={onClose}>Cancelar</Button><Button bg='#132034' color='white' onClick={salvar}>Salvar</Button></Flex></Grid></ModalBody></ModalContent></Modal>; }
export default function CentrosCusto() { const isLoggedIn = isAuthenticated(); const [items, setItems] = useState([]); const [empresas, setEmpresas] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editItem, setEditItem] = useState(null); const [deleteTarget, setDeleteTarget] = useState(null); const { isOpen, onOpen, onClose } = useDisclosure(); const { isOpen: isConfirmOpen, onOpen: onConfirmOpen, onClose: onConfirmClose } = useDisclosure(); const toast = useToast(); const cancelRef = useRef(); const carregar = async () => { try { setLoading(true); setError(''); const [centros, emps] = await Promise.all([listarCentrosCusto(), listarEmpresas()]); setItems(centros); setEmpresas(emps); } catch (e) { setError(getFriendlyError(e)); } finally { setLoading(false); } }; useEffect(() => { carregar(); }, []); const empresaMap = useMemo(() => new Map(empresas.map((e) => [String(e.id), e.nome])), [empresas]); if (!isLoggedIn) return <Navigate to='/login' />;
  const save = async (form) => { try { if (editItem) await atualizarCentroCusto(editItem.id, form); else await criarCentroCusto(form); await carregar(); toast({ title: 'Centro de custo salvo com sucesso.', status: 'success', position: 'top' }); } catch (e) { toast({ title: getFriendlyError(e), status: 'error', position: 'top' }); throw e; } };
  const remove = async () => { try { await inativarCentroCusto(deleteTarget.id); await carregar(); onConfirmClose(); } catch (e) { toast({ title: getFriendlyError(e), status: 'error', position: 'top' }); } };
  return <Box p='8' w='100%'><Box bg='white' p='6' borderRadius='xl' boxShadow='sm'><Flex justify='space-between' mb='4'><Text fontWeight='bold' fontSize='lg' color='#132034'>Centros de Custo</Text><Button bg='#132034' color='white' leftIcon={<LuPlus />} onClick={() => { setEditItem(null); onOpen(); }}>Novo Centro</Button></Flex>{loading ? <Flex justify='center' py='10'><Spinner /></Flex> : error ? <Box textAlign='center'><Text color='red.500' mb='3'>{error}</Text><Button onClick={carregar}>Tentar novamente</Button></Box> : items.length === 0 ? <Text color='gray.500'>Nenhum centro de custo cadastrado.</Text> : <TableContainer><Table><Thead><Tr><Th>Empresa</Th><Th>Nome</Th><Th>Código</Th><Th>Status</Th><Th>Ações</Th></Tr></Thead><Tbody>{items.map((item) => <Tr key={item.id}><Td>{empresaMap.get(String(item.empresaId)) || `#${item.empresaId}`}</Td><Td>{item.nome}</Td><Td>{item.codigo || '-'}</Td><Td><Badge>{item.status || 'Ativo'}</Badge></Td><Td><Menu><MenuButton as={IconButton} icon={<LuEllipsisVertical />} variant='ghost' /><MenuList><MenuItem onClick={() => { setEditItem(item); onOpen(); }}>Editar</MenuItem><MenuItem color='red.500' onClick={() => { setDeleteTarget(item); onConfirmOpen(); }}>Inativar</MenuItem></MenuList></Menu></Td></Tr>)}</Tbody></Table></TableContainer>}</Box><CentroModal isOpen={isOpen} onClose={onClose} onSave={save} initialData={editItem} empresas={empresas} /><AlertDialog isOpen={isConfirmOpen} leastDestructiveRef={cancelRef} onClose={onConfirmClose}><AlertDialogOverlay><AlertDialogContent><AlertDialogHeader>Inativar Centro de Custo</AlertDialogHeader><AlertDialogBody>Tem certeza?</AlertDialogBody><AlertDialogFooter><Button ref={cancelRef} onClick={onConfirmClose}>Cancelar</Button><Button colorScheme='red' onClick={remove}>Inativar</Button></AlertDialogFooter></AlertDialogContent></AlertDialogOverlay></AlertDialog></Box>; }
