import React, { useEffect, useRef, useState } from 'react';
import { AlertDialog, AlertDialogBody, AlertDialogContent, AlertDialogFooter, AlertDialogHeader, AlertDialogOverlay, Badge, Box, Button, Flex, FormControl, FormErrorMessage, FormLabel, Grid, IconButton, Input, Menu, MenuButton, MenuItem, MenuList, Modal, ModalBody, ModalCloseButton, ModalContent, ModalHeader, ModalOverlay, Select, Spinner, Table, TableContainer, Tbody, Td, Text, Th, Thead, Tr, useDisclosure, useToast } from '@chakra-ui/react';
import { LuEllipsisVertical, LuPlus } from 'react-icons/lu';
import { Navigate } from 'react-router-dom';
import { isAuthenticated } from '../../utils/session';
import { atualizarCategoriaFinanceira, criarCategoriaFinanceira, inativarCategoriaFinanceira, listarCategoriasFinanceiras } from '../../services/categoriasFinanceiras.service';
const EMPTY_FORM = { nome: '', tipo: 'RECEITA', cor: '', status: 'Ativo' };
const getFriendlyError = (e) => e?.data?.message || e?.message || 'Não foi possível concluir a ação.';
function CategoriaModal({ isOpen, onClose, onSave, initialData }) { const [form, setForm] = useState(EMPTY_FORM); const [errors, setErrors] = useState({}); useEffect(() => { setForm(initialData ? { ...EMPTY_FORM, ...initialData } : EMPTY_FORM); setErrors({}); }, [isOpen, initialData]); const ch = (e) => setForm((p) => ({ ...p, [e.target.name]: e.target.value })); const salvar = async () => { const next = {}; if (!form.nome?.trim()) next.nome = 'Nome obrigatório'; if (!form.tipo) next.tipo = 'Tipo obrigatório'; setErrors(next); if (Object.keys(next).length) return; try { await onSave(form); onClose(); } catch {} };
  return <Modal isOpen={isOpen} onClose={onClose} isCentered><ModalOverlay /><ModalContent><ModalHeader>{initialData ? 'Editar Categoria Financeira' : 'Nova Categoria Financeira'}</ModalHeader><ModalCloseButton /><ModalBody pb='6'><Grid gap='3'><FormControl isRequired isInvalid={!!errors.nome}><FormLabel>Nome</FormLabel><Input name='nome' value={form.nome} onChange={ch} /><FormErrorMessage>{errors.nome}</FormErrorMessage></FormControl><FormControl isRequired isInvalid={!!errors.tipo}><FormLabel>Tipo</FormLabel><Select name='tipo' value={form.tipo} onChange={ch}><option value='RECEITA'>RECEITA</option><option value='DESPESA'>DESPESA</option></Select><FormErrorMessage>{errors.tipo}</FormErrorMessage></FormControl><FormControl><FormLabel>Cor</FormLabel><Input name='cor' value={form.cor} onChange={ch} placeholder='#132034' /></FormControl><FormControl><FormLabel>Status</FormLabel><Select name='status' value={form.status} onChange={ch}><option>Ativo</option><option>Inativo</option></Select></FormControl><Flex justify='flex-end' gap='3'><Button variant='ghost' onClick={onClose}>Cancelar</Button><Button bg='#132034' color='white' onClick={salvar}>Salvar</Button></Flex></Grid></ModalBody></ModalContent></Modal>; }
export default function CategoriasFinanceiras() { const isLoggedIn = isAuthenticated(); const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editItem, setEditItem] = useState(null); const [deleteTarget, setDeleteTarget] = useState(null); const { isOpen, onOpen, onClose } = useDisclosure(); const { isOpen: isConfirmOpen, onOpen: onConfirmOpen, onClose: onConfirmClose } = useDisclosure(); const toast = useToast(); const cancelRef = useRef(); const carregar = async () => { try { setLoading(true); setError(''); setItems(await listarCategoriasFinanceiras()); } catch (e) { setError(getFriendlyError(e)); } finally { setLoading(false); } }; useEffect(() => { carregar(); }, []); if (!isLoggedIn) return <Navigate to='/login' />;
  const save = async (form) => { try { if (editItem) await atualizarCategoriaFinanceira(editItem.id, form); else await criarCategoriaFinanceira(form); await carregar(); toast({ title: 'Categoria salva com sucesso.', status: 'success', position: 'top' }); } catch (e) { toast({ title: getFriendlyError(e), status: 'error', position: 'top' }); throw e; } };
  const remove = async () => { try { await inativarCategoriaFinanceira(deleteTarget.id); await carregar(); onConfirmClose(); } catch (e) { toast({ title: getFriendlyError(e), status: 'error', position: 'top' }); } };
  return <Box p='8' w='100%'><Box bg='white' p='6' borderRadius='xl' boxShadow='sm'><Flex justify='space-between' mb='4'><Text fontWeight='bold' fontSize='lg' color='#132034'>Categorias Financeiras</Text><Button bg='#132034' color='white' leftIcon={<LuPlus />} onClick={() => { setEditItem(null); onOpen(); }}>Nova Categoria</Button></Flex>{loading ? <Flex justify='center' py='10'><Spinner /></Flex> : error ? <Box textAlign='center'><Text color='red.500' mb='3'>{error}</Text><Button onClick={carregar}>Tentar novamente</Button></Box> : items.length === 0 ? <Text color='gray.500'>Nenhuma categoria financeira cadastrada.</Text> : <TableContainer><Table><Thead><Tr><Th>Nome</Th><Th>Tipo</Th><Th>Cor</Th><Th>Status</Th><Th>Ações</Th></Tr></Thead><Tbody>{items.map((item) => <Tr key={item.id}><Td>{item.nome}</Td><Td><Badge colorScheme={item.tipo === 'RECEITA' ? 'green' : 'red'}>{item.tipo}</Badge></Td><Td>{item.cor || '-'}</Td><Td><Badge>{item.status || 'Ativo'}</Badge></Td><Td><Menu><MenuButton as={IconButton} icon={<LuEllipsisVertical />} variant='ghost' /><MenuList><MenuItem onClick={() => { setEditItem(item); onOpen(); }}>Editar</MenuItem><MenuItem color='red.500' onClick={() => { setDeleteTarget(item); onConfirmOpen(); }}>Inativar</MenuItem></MenuList></Menu></Td></Tr>)}</Tbody></Table></TableContainer>}</Box><CategoriaModal isOpen={isOpen} onClose={onClose} onSave={save} initialData={editItem} /><AlertDialog isOpen={isConfirmOpen} leastDestructiveRef={cancelRef} onClose={onConfirmClose}><AlertDialogOverlay><AlertDialogContent><AlertDialogHeader>Inativar Categoria</AlertDialogHeader><AlertDialogBody>Tem certeza?</AlertDialogBody><AlertDialogFooter><Button ref={cancelRef} onClick={onConfirmClose}>Cancelar</Button><Button colorScheme='red' onClick={remove}>Inativar</Button></AlertDialogFooter></AlertDialogContent></AlertDialogOverlay></AlertDialog></Box>; }
