import React, { useEffect, useRef, useState } from 'react';
import { Box, Flex, Text, Badge, Input, Select, Button, Table, Thead, Tbody, Tr, Th, Td, TableContainer, Modal, ModalOverlay, ModalContent, ModalHeader, ModalBody, ModalCloseButton, FormControl, FormLabel, FormErrorMessage, Grid, useDisclosure, useToast, Spinner, AlertDialog, AlertDialogBody, AlertDialogFooter, AlertDialogHeader, AlertDialogContent, AlertDialogOverlay, Menu, MenuButton, MenuList, MenuItem, IconButton } from '@chakra-ui/react';
import { LuPlus, LuEllipsisVertical } from 'react-icons/lu';
import { Navigate } from 'react-router-dom';
import { isAuthenticated } from '../../utils/session';
import { atualizarBanco, criarBanco, inativarBanco, listarBancos } from '../../services/bancos.service';
const EMPTY_FORM = { codigo: '', nome: '', ispb: '', status: 'Ativo' }; const getFriendlyError = (e) => e?.data?.message || e?.message || 'Não foi possível concluir a ação.';
function BancoModal({ isOpen, onClose, onSave, initialData }) { const [form, setForm] = useState(initialData || EMPTY_FORM); const [errors, setErrors] = useState({}); useEffect(() => { setForm(initialData || EMPTY_FORM); setErrors({}); }, [initialData, isOpen]); const ch = (e) => setForm((p) => ({ ...p, [e.target.name]: e.target.value })); async function salvar() { const e = {}; if (!form.nome?.trim()) e.nome = 'Nome obrigatório'; if (!form.codigo?.trim()) e.codigo = 'Código obrigatório'; if (Object.keys(e).length) return setErrors(e); try { await onSave(form); onClose(); } catch {} }
  return <Modal isOpen={isOpen} onClose={onClose} isCentered><ModalOverlay /><ModalContent><ModalHeader>{initialData ? 'Editar Banco' : 'Novo Banco'}</ModalHeader><ModalCloseButton /><ModalBody pb='6'><Grid gap='3'><FormControl isRequired isInvalid={!!errors.codigo}><FormLabel>Código</FormLabel><Input name='codigo' value={form.codigo} onChange={ch} /><FormErrorMessage>{errors.codigo}</FormErrorMessage></FormControl><FormControl isRequired isInvalid={!!errors.nome}><FormLabel>Nome</FormLabel><Input name='nome' value={form.nome} onChange={ch} /><FormErrorMessage>{errors.nome}</FormErrorMessage></FormControl><FormControl><FormLabel>ISPB</FormLabel><Input name='ispb' value={form.ispb} onChange={ch} /></FormControl><FormControl><FormLabel>Status</FormLabel><Select name='status' value={form.status} onChange={ch}><option>Ativo</option><option>Inativo</option></Select></FormControl><Flex justify='flex-end' gap='3'><Button variant='ghost' onClick={onClose}>Cancelar</Button><Button bg='#132034' color='white' onClick={salvar}>Salvar</Button></Flex></Grid></ModalBody></ModalContent></Modal>; }
export default function Bancos() { const isLoggedIn = isAuthenticated(); const [bancos, setBancos] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [filters, setFilters] = useState({ nome: '', status: '' }); const [editItem, setEditItem] = useState(null); const [deleteTarget, setDeleteTarget] = useState(null); const { isOpen, onOpen, onClose } = useDisclosure(); const { isOpen: isConfirmOpen, onOpen: onConfirmOpen, onClose: onConfirmClose } = useDisclosure(); const toast = useToast(); const cancelRef = useRef(); const carregar = async () => { try { setLoading(true); setError(''); setBancos(await listarBancos()); } catch (err) { setError(getFriendlyError(err)); } finally { setLoading(false); } }; useEffect(() => { carregar(); }, []); if (!isLoggedIn) return <Navigate to='/login' />;
  const filtered = bancos.filter((b) => (!filters.nome || b.nome.toLowerCase().includes(filters.nome.toLowerCase())) && (!filters.status || (b.status || 'Ativo') === filters.status));
  const save = async (form) => { try { if (editItem) await atualizarBanco(editItem.id, form); else await criarBanco(form); await carregar(); toast({ title: 'Banco salvo com sucesso.', status: 'success', position: 'top' }); } catch (err) { toast({ title: getFriendlyError(err), status: 'error', position: 'top' }); throw err; } };
  const remove = async () => { try { await inativarBanco(deleteTarget.id); await carregar(); onConfirmClose(); } catch (err) { toast({ title: getFriendlyError(err), status: 'error', position: 'top' }); } };
  return <Box p='8' w='100%'><Box bg='white' p='6' borderRadius='xl'><Flex justify='space-between' mb='4'><Text fontWeight='bold'>Bancos</Text><Button leftIcon={<LuPlus />} onClick={() => { setEditItem(null); onOpen(); }}>Novo Banco</Button></Flex><Flex gap='3' mb='4'><Input placeholder='Buscar por nome' maxW='260px' value={filters.nome} onChange={(e) => setFilters((p) => ({ ...p, nome: e.target.value }))} /><Select placeholder='Status' maxW='140px' value={filters.status} onChange={(e) => setFilters((p) => ({ ...p, status: e.target.value }))}><option value='Ativo'>Ativo</option><option value='Inativo'>Inativo</option></Select><Button size='sm' onClick={() => setFilters({ nome: '', status: '' })}>Limpar</Button></Flex>{loading ? <Flex justify='center' py='10'><Spinner /></Flex> : error ? <Box textAlign='center'><Text color='red.500'>{error}</Text><Button onClick={carregar}>Tentar novamente</Button></Box> : filtered.length === 0 ? <Text color='gray.500'>Nenhum banco encontrado.</Text> : <TableContainer><Table><Thead><Tr><Th>Código</Th><Th>Nome</Th><Th>ISPB</Th><Th>Status</Th><Th>Ações</Th></Tr></Thead><Tbody>{filtered.map((b) => <Tr key={b.id}><Td>{b.codigo || '-'}</Td><Td>{b.nome}</Td><Td>{b.ispb || '-'}</Td><Td><Badge>{b.status || 'Ativo'}</Badge></Td><Td><Menu><MenuButton as={IconButton} icon={<LuEllipsisVertical />} variant='ghost' /><MenuList><MenuItem onClick={() => { setEditItem(b); onOpen(); }}>Editar</MenuItem><MenuItem color='red.500' onClick={() => { setDeleteTarget(b); onConfirmOpen(); }}>Inativar</MenuItem></MenuList></Menu></Td></Tr>)}</Tbody></Table></TableContainer>}</Box><BancoModal isOpen={isOpen} onClose={onClose} onSave={save} initialData={editItem} /><AlertDialog isOpen={isConfirmOpen} leastDestructiveRef={cancelRef} onClose={onConfirmClose}><AlertDialogOverlay><AlertDialogContent><AlertDialogHeader>Inativar Banco</AlertDialogHeader><AlertDialogBody>Tem certeza?</AlertDialogBody><AlertDialogFooter><Button ref={cancelRef} onClick={onConfirmClose}>Cancelar</Button><Button colorScheme='red' onClick={remove}>Inativar</Button></AlertDialogFooter></AlertDialogContent></AlertDialogOverlay></AlertDialog></Box>; }
